name: "Build electron executables"
on: 
  push:
    branches: 
      - main
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt update
          sudo apt install --install-recommends winehq-stable
      # Checkout and install
      - name: checkout
        uses: actions/checkout@v2
      - name: NPM Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install deps
        run: npm install
      # Build and deploy
      - name: Build frontend
        run: npx nx build core --prod
        env:
          COMEN_ENVIRONMENT: "electron"
      - name: Build electron app
        run: npx nx build electron-app --prod
      - name: Package electron app
        run: npm run build-electron-win
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: dist/executables/Comen.exe
          
