name: "Vercel staging deployment for node backend"
on: [pull_request] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout and install
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm install
      # Build and deploy
      - name: Build frontend
        run: pnpx nx build core --prod
      - name: Build frontend again # wtf?
        run: pnpx nx build core --prod --skip-nx-cache
      - name: Build backend
        run: pnpx nx build node-backend --prod
      - name: Deploy production
        uses: amondnet/vercel-action@v19
        id: vercel-action-staging
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_SCOPE }}
          
